/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import javax.swing.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import models.Pessoa;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import org.hibernate.query.Query;
import javax.swing.text.MaskFormatter;
/**
 *
 * @author ADMIN
 */
public class EdicaoPessoa extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private SessionFactory sessionFactory;
    private Pessoa pessoaAtual;
    private GerenciarPessoa gerenciarPessoa;
    // Método para configurar máscaras de CPF e Telefone
    private void configurarMascaras() {
        try {
            // Máscara para CPF
            MaskFormatter cpfMask = new MaskFormatter("###.###.###-##");
            cpfMask.install(textFieldCpf); // Aplica a máscara ao campo CPF

            // Máscara para Telefone
            MaskFormatter telefoneMask = new MaskFormatter("(##) #####-####");
            telefoneMask.install(textFieldTelefone); // Aplica a máscara ao campo Telefone
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public EdicaoPessoa(GerenciarPessoa gerenciarPessoa) {
    
        initComponents();
        this.gerenciarPessoa = gerenciarPessoa;
        sessionFactory = new Configuration().configure("hibernate.cfg.xml").buildSessionFactory();
        configurarMascaras();
        carregarUsuario();
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        painelHome = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textFieldId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cancelarButton = new javax.swing.JButton();
        salvarButton = new javax.swing.JButton();
        textFieldCpf = new javax.swing.JFormattedTextField();
        textFieldTelefone = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Home"); // NOI18N
        setResizable(false);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelHome.setBackground(new java.awt.Color(255, 255, 255));
        painelHome.setForeground(new java.awt.Color(0, 0, 0));
        painelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ID:");
        painelHome.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        textFieldId.setEditable(false);
        textFieldId.setBackground(new java.awt.Color(255, 255, 255));
        textFieldId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textFieldId.setForeground(new java.awt.Color(0, 0, 0));
        textFieldId.setFocusable(false);
        painelHome.add(textFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 40, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nome:");
        painelHome.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, -1));

        textFieldNome.setBackground(new java.awt.Color(255, 255, 255));
        textFieldNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textFieldNome.setForeground(new java.awt.Color(0, 0, 0));
        painelHome.add(textFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 480, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("CPF:");
        painelHome.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 70, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Telefone:");
        painelHome.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 120, -1));

        cancelarButton.setBackground(new java.awt.Color(255, 51, 51));
        cancelarButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cancelarButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelarButton.setText("CANCELAR");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });
        painelHome.add(cancelarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 130, 60));

        salvarButton.setBackground(new java.awt.Color(255, 51, 51));
        salvarButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salvarButton.setForeground(new java.awt.Color(255, 255, 255));
        salvarButton.setText("SALVAR");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });
        painelHome.add(salvarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 130, 60));

        textFieldCpf.setBackground(new java.awt.Color(255, 255, 255));
        textFieldCpf.setForeground(new java.awt.Color(0, 0, 0));
        textFieldCpf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        painelHome.add(textFieldCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 480, 30));

        textFieldTelefone.setBackground(new java.awt.Color(255, 255, 255));
        textFieldTelefone.setForeground(new java.awt.Color(0, 0, 0));
        textFieldTelefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        painelHome.add(textFieldTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 480, 30));

        jPanel3.add(painelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        salvarAlteracoes();
    }//GEN-LAST:event_salvarButtonActionPerformed
    // Adicione o parâmetro no construtor
    
    public EdicaoPessoa(Pessoa model) {
}
       
 
    /**
     * @param args the command line arguments\
     */
   public static void main(String args[]) {
    // Configuração do Look and Feel
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    }catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(EdicaoPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

    // Criação da View e do Model
    
    Pessoa model = new Pessoa();

    // \Exibe a View
    
    }
   
   private void carregarUsuario() {
        try (BufferedReader reader = new BufferedReader(new FileReader("pessoaToEdit.txt"))) {
            String linha = reader.readLine();
            int pessoaId = Integer.parseInt(linha);

            Session session = sessionFactory.openSession();
            Transaction transaction = null;
            try {
                transaction = session.beginTransaction();

                Query<Pessoa> query = session.createQuery("FROM Pessoa WHERE id = :id", Pessoa.class);
                query.setParameter("id", pessoaId);
                pessoaAtual = query.uniqueResult();

                if (pessoaAtual != null) {
                    // Preenche os campos com as informações do usuário
                    textFieldId.setText(String.valueOf(pessoaAtual.getId()));
                    textFieldNome.setText(pessoaAtual.getNome());
                    textFieldCpf.setText(pessoaAtual.getCpf());
                    textFieldTelefone.setText(pessoaAtual.getTelefone());
                } else {
                    JOptionPane.showMessageDialog(this, "Usuário não encontrado.");
                }

                transaction.commit();
            } catch (Exception e) {
                if (transaction != null) transaction.rollback();
                e.printStackTrace();
            } finally {
                session.close();
            }

        } catch (IOException | NumberFormatException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao carregar o ID do usuário.");
        }
    }

    private void salvarAlteracoes() {
        if (pessoaAtual == null) {
            JOptionPane.showMessageDialog(this, "Nenhum usuário carregado.");
            return;
        }

        String novoNome = textFieldNome.getText();
        String novoCpf = textFieldCpf.getText();
        String novoTelefone = textFieldTelefone.getText();

        Session session = sessionFactory.openSession();
        Transaction transaction = null;
        try {
            transaction = session.beginTransaction();

            // Verifica e atualiza os valores, se necessário
            if (!pessoaAtual.getNome().equals(novoNome)) {
                pessoaAtual.setNome(novoNome);
            }
            if (!pessoaAtual.getCpf().equals(novoCpf)) {
                pessoaAtual.setCpf(novoCpf);
            }
            if (!pessoaAtual.getTelefone().equals(novoTelefone)) {
                pessoaAtual.setTelefone(novoTelefone);
            }
            

            session.update(pessoaAtual);
            transaction.commit();

            JOptionPane.showMessageDialog(this, "Informações atualizadas com sucesso.");
        } catch (Exception e) {
            if (transaction != null) transaction.rollback();
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao salvar alterações.");
        } finally {
            if (gerenciarPessoa != null) {
            gerenciarPessoa.atualizarTabela();
            }
            session.close();
            this.dispose();
        }
        
    }

    @Override
    public void dispose() {
        super.dispose();
        if (sessionFactory != null) {
            sessionFactory.close();
        }
    }

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel painelHome;
    private javax.swing.JButton salvarButton;
    private javax.swing.JFormattedTextField textFieldCpf;
    private javax.swing.JTextField textFieldId;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JFormattedTextField textFieldTelefone;
    // End of variables declaration//GEN-END:variables
}