/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import models.Usuario;
import views.CadastroUser;
import views.Login;
import controllers.UsuarioDAO;
import javax.swing.JOptionPane;
/**
 *
 * @author ADMIN
 */
public class EdicaoUser extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
   
    public EdicaoUser() {
    
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        painelHome = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textFieldId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textFieldUsuario = new javax.swing.JTextField();
        textFieldSenha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Home"); // NOI18N
        setResizable(false);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelHome.setBackground(new java.awt.Color(255, 255, 255));
        painelHome.setForeground(new java.awt.Color(0, 0, 0));
        painelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ID:");
        painelHome.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        textFieldId.setEditable(false);
        textFieldId.setBackground(new java.awt.Color(255, 255, 255));
        textFieldId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textFieldId.setForeground(new java.awt.Color(0, 0, 0));
        textFieldId.setFocusable(false);
        painelHome.add(textFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nome:");
        painelHome.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, -1));

        textFieldNome.setBackground(new java.awt.Color(255, 255, 255));
        textFieldNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textFieldNome.setForeground(new java.awt.Color(0, 0, 0));
        textFieldNome.setFocusable(false);
        painelHome.add(textFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 480, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Usuário:");
        painelHome.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 70, -1));

        textFieldUsuario.setBackground(new java.awt.Color(255, 255, 255));
        textFieldUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textFieldUsuario.setForeground(new java.awt.Color(0, 0, 0));
        textFieldUsuario.setFocusable(false);
        painelHome.add(textFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 480, -1));

        textFieldSenha.setBackground(new java.awt.Color(255, 255, 255));
        textFieldSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textFieldSenha.setForeground(new java.awt.Color(0, 0, 0));
        textFieldSenha.setFocusable(false);
        painelHome.add(textFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 480, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Senha:");
        painelHome.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 70, -1));

        jPanel3.add(painelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public EdicaoUser(Usuario model) {
}
       
 
    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    // Configuração do Look and Feel
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    }catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(EdicaoUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    // Criação da View e do Model
    EdicaoUser view = new EdicaoUser();
    Usuario model = new Usuario();

    // Exibe a View
    view.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel painelHome;
    private javax.swing.JTextField textFieldId;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JTextField textFieldSenha;
    private javax.swing.JTextField textFieldUsuario;
    // End of variables declaration//GEN-END:variables
}